default: styles/mastodon_colorides.scss
sediroloc: styles/sediroloc.scss
mastodon: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
rosaceae: styles/pink.scss
quartzo: styles/light_pink.scss
sunset: styles/sunset.scss
colorwave: styles/colorwave.scss
teal: styles/teal.scss
flamingo: styles/flamingo.scss
purple-haze: styles/purple_haze.scss
#win95: styles/win95.scss
meemu-purple: styles/meemu-default.scss
meemu-vaporwave: styles/meemu.scss
